file_path: /home/mj/projects/MTB/runs/task_14.xlsx
app_id: cli_a8c08773081fd00b
app_secret: 6MhBjUyv47NH4jHlFuMCjdC8M5xCMm61
sync_mode: clone
index_column: smCode
batch_size: 1000
rate_limit_delay: 0.5
max_retries: 3
log_level: INFO
field_type_strategy: intelligence
create_missing_fields: true
target_type: bitable
app_token: IlzLbZvwEaKKOTsxvNVc5U5DnEh
table_id: tbllDsFo4f2S1hkS
