file_path: runs/task_16.xlsx
app_id: cli_a8c08773081fd00b
app_secret: 6MhBjUyv47NH4jHlFuMCjdC8M5xCMm61
sync_mode: full
index_column: 工单号
batch_size: 1000
rate_limit_delay: 0.5
max_retries: 3
log_level: INFO
field_type_strategy: base
create_missing_fields: true
target_type: bitable
app_token: Ll6RbKd3jag8AKsWxCrc0LZmnAg
table_id: tblJP6vv2loh4if3
