file_path: runs/task_3.xlsx
app_id: cli_a8c08773081fd00b
app_secret: 6MhBjUyv47NH4jHlFuMCjdC8M5xCMm61
sync_mode: full
index_column: id
batch_size: 1000
rate_limit_delay: 0.5
max_retries: 3
log_level: INFO
field_type_strategy: intelligence
create_missing_fields: true
target_type: bitable
app_token: MRiTb2uEta08pRslTj8cHj3Qnsc
table_id: tbltdI6fxxpqKej2
